- name: Copy default HTML file for site
  tags: [apache, apache2, httpd]
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'

- name: Install Apache and PHP for Ubuntu servers
  tags: [apache, apache2, ubuntu]
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install Apache and PHP for CentOS servers
  tags: [apache, apache2, centos]
  yum:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "CentOS"

